### ISSUE TITLE
feat: Card styling feature for book club page

### ISSUE THREAD

**Issue by parisa-0** [WomenCodingCommunity/WomenCodingCommunity.github.io#108]
### Is your feature request related to a problem? Please describe.
Update the way books are being listed on the Book Club page.

### Describe the solution you'd like
Use the **[card "component" in this file](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/blob/c4d09966736405d24cb5f5f6042e881a864deda1/blog.html#L20)** and modify to have 3 or 4 cards per row for big screens. So, we'd have:

- the book title,
- Author(s) as subtext
- brief book description,
- image of the book
- the whole card should link to an online website that readers can buy the book from

### Describe alternatives you've considered
Suggestions for improvement are welcome. Please implement any suggestions you have and add screenshots to the PR.

**Comment by parisa-0** [comment]
I can take this one

**Comment by lilyndk** [comment]
Similar card styles are currently worked in https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/98. Thus, please wait for that to be done. Then we can just reuse those card styles.

**Comment by khairahscorner** [comment]
@parisa-0 I have updated the description for this issue✅. Would you still like to work on it?

**Comment by parisa-0** [comment]
Hi @khairahscorner I would like to work on this but spoke to @lilyndk and she mentioned that it's a big issue, if you're happy for me to continue working on it then assign to me otherwise I think Lily will take it

**Comment by lilyndk** [comment]
Hi, yes as discussed earlier with @parisa-0 , I will take on this. Thanks cc @khairahscorner

**Comment by lilyndk** [comment]
@khairahscorner do we have content for other books besides the one book currently listed under https://womencodingcommunity.com/program-book-club ?

**Comment by lilyndk** [comment]
@khairahscorner I'm also wondering if we should avoid including book images for now in terms of copyright issues

**Comment by dricazenck** [comment]
I don't think is a problem, considering we are promoting the books. I am wondering if this task now can be closed after your fixes @lilyndk ?

**Comment by lilyndk** [comment]
@dricazenck PR created for the styles: https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/pull/233
