### ISSUE TITLE
bug: menu dropdown link list item container should be clickable

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#112]
### Describe the bug
When you open the dropdown under one of the main links, the whole 'link list item' container is not clickable. Only the text itself is clickable (see screenshot).

### Expected behavior
Whole menu list item area is clickable with a light gray background appearing on hover. Similar 'behavior' to this mockup:
<img width="412" alt="Screenshot 2024-04-27 at 16 41 56" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/7da03583-409f-46ab-8778-abec479e48de">

### Screenshots
<img width="1568" alt="Screenshot 2024-04-27 at 16 35 25 1" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/332f943a-bcd7-4a58-9811-cb4abf990004">

### Reproducibility
- [X] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [X] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

**Comment by PaulineNemchak** [comment]
I can work on this if it's still available

**Comment by lilyndk** [comment]
@PaulineNemchak Great, thanks. Issue is assigned to you :)

**Comment by PaulineNemchak** [comment]
@lilyndk yeah thank you, I'm working on it
