### ISSUE TITLE
feat: create breadcrumbs

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#114]
### Is your feature request related to a problem? Please describe.
We need breadcrumbs to make the parent / child relationship more clear.

### Acceptance Criteria
- Create breadcrumbs component with styles in a separate _breadcrumbs.scss file.
- Use colour variables in custom/_variables.scss 
- Designs and specs:
![DEV_breadcrumbs-basic-pg](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/076da52f-5ccb-4cdf-95ca-76852d4b1c8d)
![DEV_breadcrumbs-basic-pg-with-specs](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/4fb3c3bf-bbda-4704-b1c0-09ab362c1e68)
- For blog posts with usually much longer page titles, we want to display "Back to Blog" link (if this is too 'tricky' to include in this PR, we can create a follow up ticket for this later):
![DEV_breadcrumbs-blog_post](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/dc395e81-0e04-4eb6-9319-9faa9fa64dd7)

**Comment by cathy-codes** [comment]
I can help with this.

**Comment by lilyndk** [comment]
@cathy-codes Great, it's assigned to you now :)

**Comment by lilyndk** [comment]
Hi @cathy-codes, I need to make some adjustments to the design. I'll let you know when it's done, thanks.

**Comment by lilyndk** [comment]
@cathy-codes I've updated the description and it's now ready for development, thanks.

**Comment by cathy-codes** [comment]
Link to Figma: https://www.figma.com/file/ncdevYZK7NGuTK3hc6mP4e/WCC-Design-Kit-(in-progress)?type=design&node-id=55437-28055&mode=design&t=esxhB33uOWWKd0U9-4

**Comment by lilyndk** [comment]
Hi @cathy-codes, fyi a lot of component refactoring changes have been merged today related to branding re-design, thus please ensure to pull down latest changes from main branch, thanks.
