### ISSUE TITLE
bug: Fix Inaccessible Navigation

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#115]
### Describe the bug
Issues:
1) Dropdown does not follow common UX pattern with 'Overview' page link, resulting in confusion about what pages 'exist' when the dropdown is open.
<img width="1458" alt="Screenshot 2024-04-28 at 09 38 46" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/902862a8-c874-4b22-a16f-3b072f69fb42">

2) Submenu links are not accessible from keyboard and missing aria attributes

3) Submenu items are not accessible on mobile
- Tapping on any menu item on mobile to reveal its subitems leads users to the top-level page and doesn’t give them the opportunity to browse or access any secondary pages. The user should be able to tap on top-level menu items without navigating to the page. User should be able to access sub-menu items by tapping instead.
![WhatsApp Video 2024-05-01 at 09 41 18](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/6668406/8fb90098-e7f4-41c0-890e-e9370ec5fcbe)

### Acceptance Criteria
1) Update nav to include ‘Overview’ page links. If a user clicks on the main link (e.g. About Us), the behaviour should be that the dropdown simply opens upon the click, similar to [Nielsen Norman Group](https://www.nngroup.com/):
<img width="950" alt="Screenshot 2024-04-28 at 08 02 01" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/01dd771d-843d-44db-aa26-c80d893151ea">

- Accessibility-wise, this patterns follows [W3's suggestion of having the parent function as a toggle](https://www.w3.org/WAI/tutorials/menus/flyout/).
- This will also fix bug no. 3, as described above under Issues.
- We use Material Design as design system reference, they also have good [guidelines on Menu implementation related to accessibility](https://m3.material.io/components/menus/accessibility).

2) Ensure that it is possible to open the submenu with the keyboard, e.g. using the arrow down key.
- [w3 tutorial:](https://www.w3.org/WAI/tutorials/menus/application-menus/)
- [another w3 tutorial](https://www.w3.org/WAI/tutorials/menus/flyout/)

**Comment by lilyndk** [comment]
@dricazenck let us know if you have other suggestions and/or if other codeowners should review this, before the task is assigned. :) Thanks

**Comment by khairahscorner** [comment]
That was the previous functionality but have a look at this issue: https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/69 
The menu functionality was changed to the current version to avoid the "duplication".  @lilyndk

**Comment by khairahscorner** [comment]
Also, if consistency is the main concern, we could create a similar landing page for when "Programmes" is clicked, we'd just need to figure out the content that goes on it.

**Comment by lilyndk** [comment]
Ah thanks for the info @khairahscorner

My main concern is the UX, i.e. that it's more common to have the dropdown simply open upon the click of the main nav link. Right now, users might think that the 'overview' pages don't exist if they just hover over the menu.

**Comment by lilyndk** [comment]
But if you know some good sites using the same nav pattern as we have implemented, please share. :)

**Comment by womencodingcommunity** [comment]
> istency is the main concern, we could create a similar landing p

I think that is a good idea, we can create programm landing page and should be fine.

**Comment by lilyndk** [comment]
Great.

Yeah I was also just looking at Google's material design guide, which is the design system we use. They use the proposed behaviour and it seems like this is also better accessibility-wise: https://m3.material.io/components/menus/accessibility. But I'm not an accessibility specialist so I also just asked Cathy to weigh in if she has input :)

**Comment by dricazenck** [comment]
Let's close this issue and it will be solved as part of #123

**Comment by lilyndk** [comment]
@dricazenck I'm re-opening this because several related 'nav accessibility' tickets' are being created.

**Comment by lilyndk** [comment]
Hi @sssoz, can you update the description in this issue to include the notes from the issue you reported in https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/143? And then just close issue #143 and make a note that it's a 'duplicate' of this issue. Thanks

**Comment by lilyndk** [comment]
Hi @PaulineNemchak, can you update the description in this issue to include the notes from the issue you reported in https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/139? And then just close issue #139 and make a note that it's a 'duplicate' of this issue. Thanks

**Comment by lilyndk** [comment]
It would be good to just fix all the related accessibility navigation issues in this one PR, since we need to change the main nav to include an 'overview page' link for the main landing pages (about us, etc.)

**Comment by ssssoz** [comment]
@lilyndk I unfortunately can’t edit this issue’s description!

**Comment by lilyndk** [comment]
@sssoz ah ok, I will update the description then to include the bugs you and @PaulineNemchak reported. :)

**Comment by lilyndk** [comment]
Description has been updated and this task is ready for development.
