### ISSUE TITLE
feat: Add active study groups to the website 

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#121]
### Task 
- Create **Active study groups** section on the Study group page
- Allow for study groups to be easily added or removed - Consider use of yaml for active study groups.

**Active study group to be listed**
**Frontend Javascript**
Description: Project based study group, working towards a shared application (including SDLC introduction, gaining more experience in reviewing PR, git etc), with guidance on different aspects like testing, CI/CD.
Mentor: [Stephanie Senoner](https://womencodingcommunity.com/mentors?keywords=Stephanie%20Senoner)
Participants: 2

**Data Analytics and Generative AI concepts**
Description - The study group focuses more on the Data Analytics and Generative AI concepts and guiding on the insights across the span of industries upskilling on relevant knowledge and practical work.
Mentor: [Kirthikka Devi Venkataram](https://womencodingcommunity.com/mentors?keywords=Kirthikka)
Participants: 3

**Fullstack (Reactjs/Nodejs + Backend in Java)**
Description: Focus on fullstack development using Java as backend
Mentor: [Hersi Kopani](https://womencodingcommunity.com/mentors?keywords=Kopani)
Participants: 6

**Backend with Java and Rust**
Description: Focus on Java including the whole developing process with creating projects and push them to git doing pairing review
Mentor: [Liliia Rafikova](https://womencodingcommunity.com/mentors?keywords=Liliia)
Participants: 5

Please note the following screenshots are old and outdated. 
**When adding this section, new colour schemes and styles should be considered.**

![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/101481898/2e13fe00-bbcc-4a88-9709-320aad457e14)

![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/101481898/02ea64e3-4c90-403b-b713-fb4a4a6dcde5)

### Acceptance criteria
Screenshot of the active study groups

**Comment by goelsonali** [comment]
All the active study group added to the website.
