### ISSUE TITLE
bug: Accessibility on Footer networks

### ISSUE THREAD

**Issue by cathy-codes** [WomenCodingCommunity/WomenCodingCommunity.github.io#122]
**Task**
Replace the h5 tag with a h2 for the "Follow Us" heading for social media, this is because it is easier for screen readers to navigate around and gets confusing when there's a h1, h2 tag then it jumps to h5 without any h3, h4 etc.

**Comment by khairahscorner** [comment]
Thanks @cathy-codes for highlighting these accessibility issues, definitely a critical aspect we all should pay more attention to🙌
Perhaps you can help contribute to address some of them. If so, you can assign yourself via a comment or the Assignees tag on the right hand side. Thanks!

**Comment by MitaliShah** [comment]
Hello, I would like to contribute if the issue is still available. Thank you!

**Comment by cathy-codes** [comment]
@MitaliShah Hey Mitali, feel free to work on this one too.
@khairahscorner Thank you for your comment Airah! More than happy to help when I have time if issues haven't been taken

**Comment by dricazenck** [comment]
I think in that case should be h3 no? ~because all titles are h2~, what do you think @khairahscorner and @lilyndk? 

Actually not all titles are h2, they are h1. But what about pages that already have h2, for example: https://womencodingcommunity.com/program-book-club ?

**Comment by MitaliShah** [comment]
I propose it could be an `<h3>`. 
I'll wait for confirmation before making the change. @dricazenck @khairahscorner @lilyndk

**Comment by cathy-codes** [comment]
In accessibility you think about the semantics/meanings of the titles. 

h1 is the main page title and it is recommended that you only have 1 of this. You can have multiple h2's (and downwards), but h3 is a sub-category of h2, h4 is a sub-category of h3 etc.

"Follow Us" isn't a sub-category of any of the existing h2's - you can take a look at some examples in accessible websites, there's HFALS (Hammersmith and Fulham Adult Learning Service) which I've worked on [https://www.hfals.ac.uk/](https://www.hfals.ac.uk/)
Or TFL (Transport for London) [https://tfl.gov.uk/](https://tfl.gov.uk/). 

Therefore I still think it should be a h2. Hope this helps everyone!

If you'd like to do more reading on accessible heading structures, this is a great site: [https://www.a11yproject.com/posts/how-to-accessible-heading-structure/](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/)

**Comment by MitaliShah** [comment]
@cathy-codes That makes sense! Thanks for a great explanation! Can I go ahead and make it `<h2>` @dricazenck?
