### ISSUE TITLE
bug: fix side-by-side card components unequal height (flexbox css issue)

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#133]
### Describe the bug
Cards on Team and Home pages have unequal heights:
<img width="1602" alt="Screenshot 2024-04-29 at 14 54 55" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/c4edd599-3fe1-4d94-95e4-e7e270a9b986">
![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/8b5475b7-e253-400d-9049-20b0c9d58947)

### Expected behavior
Side-by-side card components should always have equal heights.

**Comment by cathy-codes** [comment]
Hey @lilyndk, I've got an easy fix for this but not sure if this is what you'd want? Wondering if we should hide the card footer entirely if there's no social links.

![Screenshot 2024-04-30 195410](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/11363288/0f692a2c-73e5-456d-926d-541d3af14295) (Alt text: image showing contributor cards with the same height)

**Comment by lilyndk** [comment]
Hi @cathy-codes , yes let's hide the gray footer if there's no footer content, thanks!

**Comment by cathy-codes** [comment]
Sure, @lilyndk can you assign the task to me? Thanks!

**Comment by lilyndk** [comment]
@cathy-codes done :)
