### ISSUE TITLE
Add listed mentors to the website - Mona, Andrew, Adeola, Anastasia and Nonna

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#137]
### Task
Add the following mentors to the website
URL - https://womencodingcommunity.com/mentors

### Mentors to be added

Mona Ahluwalia
Andrew King
Adeola Adekoyejo
Anastasia
Nonna Shakhova

Reference: https://womenwhocode.github.io/london/mentors (helpful to get mentor details)

### Acceptance Criteria
Screenshot showing the mentors

**Comment by cathy-codes** [comment]
I can help with this if it's not taken.

**Comment by mads6879** [comment]
@cathy-codes fyi - In case you have picked this one up, I have added one more mentor to the list (Nonna).

**Comment by cathy-codes** [comment]
@mads6879 Sure no problem. Can you assign the task to me please?
