### ISSUE TITLE
bug: submenu links are not accessible from keyboard

### ISSUE THREAD

**Issue by PaulineNemchak** [WomenCodingCommunity/WomenCodingCommunity.github.io#139]
### Describe the bug
Submenu links are not accessible from keyboard and misses aria attributes

### To Reproduce
1. Go to the website
2. Navigate with your keyboard using tab key
3. Focus on the menu item and try to open the submenu

### Expected behavior
It should be possible to open the submenu with your keyboard e.g. using the arrow down key
[w3 tutorial:](https://www.w3.org/WAI/tutorials/menus/application-menus/)
[another w3 tutorial](https://www.w3.org/WAI/tutorials/menus/flyout/)

### Screenshots
<img width="685" alt="Screenshot 2024-04-30 at 15 13 02" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/10814016/1613869e-57c8-40e9-9029-7d8462a0c449">

### Desktop (please complete the following information):
 - OS: macOS
 - Browser tested in chrome, suppose any
 - Version 124

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [x] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

### Related Issues/PRs
If you know of any related issues or pull requests, link them here.

### Proposed Solution (optional)
If you have any ideas on how to fix the bug or potential areas to investigate, suggest them here.

### Your Contribution (optional)
If you're able and willing to contribute a fix, mention it here.

**Comment by lilyndk** [comment]
Closing this as a duplicate of https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/115

**Comment by PaulineNemchak** [comment]
Sorry @lilyndk I've missed that

**Comment by lilyndk** [comment]
No worries @PaulineNemchak :) It was also confusing how it was moved under a different ticket and now re-opened again...
