### ISSUE TITLE
Add listed mentors to the website - Shailaja, Claudia, Bryan, Jenny

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#141]
### Task
Add the following mentors to the website
URL - https://womencodingcommunity.com/mentors

### Mentors to be added
Shailaja Koppu
Claudia Lee
Bryan Boreham
Jenny Johnson

Reference: https://womenwhocode.github.io/london/mentors (helpful to get mentor details)

### Acceptance Criteria
Screenshot showing the mentors

**Comment by cathy-codes** [comment]
Messaged that @sssoz can take this
