### ISSUE TITLE
Add listed mentors to the website - Sakirat, Agoro, Tvisha, Sahana

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#142]
### Task
Add the following mentors to the website
URL - https://womencodingcommunity.com/mentors

### Mentors to be added
Sakirat Kehinde Usman
Agoro, Adegbenga
Tvisha Dholakia
Sahana Venkatesh

Reference: https://womenwhocode.github.io/london/mentors (helpful to get mentor details)

### Acceptance Criteria
Screenshot showing the mentors

**Comment by cathy-codes** [comment]
I can also take this card.
