### ISSUE TITLE
feat: Set up consent mode Banner

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#175]
### About consent mode

Consent mode allows you to send consent from end users in regions where consent regulations apply (such as end users in the EEA) to share their personal data with Google so that they can receive personalized ads and you can measure ad performance. It works by using your Google tags, which dynamically adapt to use cookies only when consent has been given by the user.

Consent mode also activates Google's conversion modeling, which fills in any gaps in conversions when observable data is not available. [Learn more about consent mode](https://support.google.com/google-ads/answer/10000067)

### Description

A consent banner is a notification that shows up on a website. It informs users about their choices for sharing their personal data.

Consent mode lets you communicate your users’ cookie or app identifier consent status to Google. Tags adjust their behaviour and respect users’ choices.

[User privacy overview ](https://developers.google.com/tag-platform/security/concepts/privacy#consent_mode_overview) 

### Solution 
[How to setup](https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#default-consent)
[advanced mode](https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#gtag.js_1)

**Comment by Deejarh** [comment]
@dricazenck  @khairahscorner i will like to work on this.

**Comment by Deejarh** [comment]
Bumping on this one @dricazenck @khairahscorner ^ Could you assign this one to me

**Comment by khairahscorner** [comment]
@Deejarh I missed this, I have assigned you if you'd still like to work on it. Do let me know if you need any additional resources

**Comment by khairahscorner** [comment]
@Deejarh thanks for resolving!🚀
