### ISSUE TITLE
Add listed mentors to the website - Liliia

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#181]
### Task
Add the following mentors to the website
URL - https://womencodingcommunity.com/mentors

### Mentors to be added
Liliia Rafikova

Reference: https://womenwhocode.github.io/london/mentors (helpful to get mentor details)

### Acceptance Criteria
Screenshot showing the mentors

**Comment by nverbic** [comment]
I can do this one if nobody is working on it already.
