### ISSUE TITLE
feat: Machine Learning program

### ISSUE THREAD

**Issue by yingliu-data** [WomenCodingCommunity/WomenCodingCommunity.github.io#187]
Under ML program page, create **Machine Learning Programme**, similar to interview preparation [CV Clinic](https://womencodingcommunity.com/program-interview-preparation#cv-clinic)

@sophia172 please provide the following information: 

- Programme Description: 
- How it works:
- Benefits of Joining: 
- Slack Channel to join and a short description to join:

**Comment by lilyndk** [comment]
Changing status of this to 'Pending' since new feature requests are on hold until the new brand colours have been implemented (https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/189).

**Comment by lilyndk** [comment]
Removing pending label, now that the branding re-design PR has been merged, thanks.

**Comment by cathy-codes** [comment]
I can possibly take this if there's a design for this page? @lilyndk

**Comment by lilyndk** [comment]
@cathy-codes @sophia172 I need clarification on the content requirements before design can be created. :) These are the questions I have:

1. Currently there is no 'ML program page' on the site, should this just be a direct child page of 'Programmes'? If yes, do we have any 'about' text to use so the page doesn't appear almost empty?
2. Currently we list upcoming and past events on the [Events page](https://womencodingcommunity.com/events). But we haven't implemented 'backend logic' yet for sorting events by date and category - should that task be a part of this feature request @dricazenck ?

**Comment by khairahscorner** [comment]
Unassigning this issue, as it has been pending without a merge for some time

**Comment by khairahscorner** [comment]
Closing this issue as it is now in #99
