### ISSUE TITLE
feat: create python script to import active events from meetup

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#192]
### Is your feature request related to a problem? Please describe.
Create python script to import data from [meetup](https://www.meetup.com/women-coding-community/) and include them into _data/events.yml 

### Describe alternatives you've considered
This script can be executed manually whenever necessary. Later the new events page will created and also could be categorised to be able to show in programmes, home (similar to announcements) and in respective new event Page. 

### Meetup Example event 
[Event example](https://www.meetup.com/women-coding-community/events/300856519/)
<img width="628" alt="image" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/d8ab510e-b857-45f0-8d47-ebd01ffa74da">

### Yml information
* Title 
* Description
* Date / hour
* Hosters
* Speakers
* expiration (until when should be shown in home page as next event) 
* Category (Mentorship, Interview Prep, BookClub, Write Club and others) 
* Banner image link 

Please check:
*   [_data/events.yml](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/blob/main/_data/events.yml) 
* [events html from home page](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/blob/main/_includes/featured-events.html)

@lilyndk Could you create a new issue with the layout for events page. 

### Extra notes
* This issue only covers the creation of yml file, not the events page. 
* Please consider create test for the script. 

### Screenshot as example
![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/105c1b42-c652-45d7-90a4-5008a5f0c528)

**Comment by dricazenck** [comment]
@lilyndk anything else you think will be necessary to be present in the events page?

**Comment by goelsonali** [comment]
@dricazenck @lilyndk - An idea, it should filter only the future events and not the past events.

**Comment by lilyndk** [comment]
@dricazenck What is meant by 'schedule' in the list under 'Yml information'?

**Comment by dricazenck** [comment]
> @dricazenck @lilyndk - An idea, it should filter only the future events and not the past events.

Yep, I was thinking in have 2 sessions like next events and past events. But I like the idea of search for events. Similar to mentors search. So we can filter per category and etc. For this version I think would be good only have all events and we can create this as part of the platform project. What do you think @lilyndk @goelsonali ?

**Comment by goelsonali** [comment]
I think we can import all events past and upcoming and just separate them under 2 sections as you mentioned @dricazenck

**Comment by dricazenck** [comment]
We cannot import past events from old community. But we can have in the same events pages past and future events, yes.

**Comment by lilyndk** [comment]
@dricazenck @goelsonali Yes, agreed.
- We can add a tabs nav to separate the events list into upcoming and past events.
- And yes, I think we should keep it simple for the site with just listing the events with simple search maybe like mentors. For platform we can add more advanced search and filtering - see the [Figma platform events page suggestion here](https://www.figma.com/proto/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-Design-System?page-id=47909%3A2&node-id=55291-27463&viewport=1033%2C-11%2C0.1&t=3tfyGac5wWSTLP1e-1&scaling=min-zoom&starting-point-node-id=55436%3A27231).

**Comment by lilyndk** [comment]
Theming task created: https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/232

PR created: https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/pull/233 . Keeping the events page list styles similar to homepage to keep it simple for now.
For platform we want to improve the UX and design with the left displayed search filter always visible on scroll ([see design prototype in Figma](https://www.figma.com/proto/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-Design-System?page-id=47909%3A2&node-id=55291-27463&viewport=1390%2C-23%2C0.09&t=yZZubDiZR4PppCwv-1&scaling=min-zoom&starting-point-node-id=55436%3A27231))
