### ISSUE TITLE
feat: Improve Google Analytics in Mentor Page and Home Page

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#222]
### Description
Currently we only added the GA tag into the website, but would be nice to have better understand of activities of users in the website. About their navigation and experience. 

#### Suggestion
Do some investigation with Google Analytics tags and introduce more tags in the website, mostly in Mentor's page and Home, so we can see for example type of queries that users search and mentors with more interactions and sessions more clicked, resources, mentors feedback and etc.

**Comment by khairahscorner** [comment]
@goelsonali is this issue resolved please? So I can either close it, thanks

**Comment by goelsonali** [comment]
No haven't been able to work on this..  Unassigned myself

**Comment by khairahscorner** [comment]
Looks like this has been done (for mentors page) by @dricazenck

**Comment by khairahscorner** [comment]
Closing as it's already resolved
