### ISSUE TITLE
feat: Allow to share blog

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#226]
Would be nice to have the possibility from specific blog page to share in social media (LindkedIn, X and others) 

@lilyndk do we have any mockup related to this?

**Comment by lilyndk** [comment]
Yes, see designs below.

Frontend implementation guidelines:
- use variables in custom/_variables.scss for theming
-- 'bar background': $bg-1 (light blue)
-- icon background: $primary
-- icon colour: $white
-- 'share text' colour: $text-secondary
- icons: we use [Google Material Symbols icons](https://fonts.google.com/icons)


<img width="1150" alt="Screenshot 2024-05-25 at 14 49 19" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/f255458e-b3f5-4242-8d0b-ce123c3da4d4">

<img width="1150" alt="Screenshot 2024-05-25 at 14 48 56" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/155481ba-86f8-41f2-b8a8-3a2687428160">

<img width="345" alt="Screenshot 2024-05-25 at 14 49 52" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/c96201f2-06a7-4578-af8a-f418b70aef5b">
