### ISSUE TITLE
feat: Allow to share Mentor Profile

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#227]
### Is your feature request related to a problem?
Would be nice to have the possible to users share a mentor profile in social media and to copy their profile link. 

The profile link is: http://womencodingcommunity.com/mentors?keywords=MENTOR_NAME

For example: http://womencodingcommunity.com/mentors?keywords=Adriana

@lilyndk any suggestion about mockup?

**Comment by lilyndk** [comment]
Yes, see the designs below.

Frontend implementation guidelines:
- use variables in custom/_variables.scss for theming
-- dropdown text and icon colour: $text-secondary
- icons: we use [Google Material Symbols icons](https://fonts.google.com/icons)

![mentor-card-share-link](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/0dcb48cf-a9de-40b7-a8db-2802e3cb04f7)

![mentor-card-share-link_btn-dropdown](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/56ed3e7e-05d7-43cd-bfb2-8fb99fa50ac5)

**Comment by Deejarh** [comment]
@khairahscorner  kindy assign to me

**Comment by khairahscorner** [comment]
Thanks for taking care @Deejarh 🙌
