### ISSUE TITLE
bug: Incident report form link missing on Code of Conduct page

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#228]
## Acceptance Criteria
Missing link is added to the 'Enforcement' section of the https://womencodingcommunity.com/code-of-conduct page.

<img width="1327" alt="Screenshot 2024-05-18 at 15 13 01" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/358cd6dc-f2e7-49f5-92b1-249f3a9f27f6">

**Comment by lilyndk** [comment]
@dricazenck Do you know what form link should be used here?

**Comment by dricazenck** [comment]
> @dricazenck Do you know what form link should be used here?

I think it should send us an email to london@

**Comment by dricazenck** [comment]
That is your task @JanePB I guess first this is done, I can assign you directly to the task.
