### ISSUE TITLE
Add events to the website 

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#244]
Hi there, could you please add the two following events to the website :) 

https://www.meetup.com/women-coding-community/events/301218272/

https://www.meetup.com/women-coding-community/events/301301532/

Many thanks!

**Comment by khairahscorner** [comment]
@jbabahin can we get square highlight images like the attached screenshot for adding the events?
<img width="1223" alt="Screenshot 2024-05-30 at 8 30 29 am" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/38109438/4d6010bb-c932-4204-88d5-aaddfac3bbb1">
