### ISSUE TITLE
bug: Wrong alignment with plus (+) icon

### ISSUE THREAD

**Issue by jpmaHub** [WomenCodingCommunity/WomenCodingCommunity.github.io#248]
### Describe the bug
The plus (+) icon bullet points are misaligned with the texts. 

### To Reproduce
1. Go to [mentorshipfaq](https://womencodingcommunity.com/mentorship-faq) page
2. Go to [InterviewPreparation](https://womencodingcommunity.com/program-interview-preparation) page

### Screenshots

<img width="869" alt="Screenshot 2024-05-30 at 09 34 52" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/17250560/c1f3f0b8-cc98-4c77-a106-c3eb9b470fd2">
<img width="865" alt="Screenshot 2024-06-01 at 18 16 56" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/17250560/3a022b33-c820-413b-a962-bd5d747057eb">

### Expected behavior
The plus (+) icon bullet points should be aligned with the texts on the right side as the screenshots below:  
![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/d0a988c8-b757-465f-9a49-b30c7255f0a4)

![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/9cdfa8b4-7567-423f-b13f-99822694e238)

### Desktop (please complete the following information):
 - OS:  iOS
 - Browser: Safari and Firefox 

### Reproducibility
- [x] The bug is reproducible consistently.

### Impact
- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [x] The bug is a cosmetic issue.

### Your Contribution
I am willing to contribute a fix.

**Comment by dricazenck** [comment]
@lilyndk just you know as well, I assigned to @jpmaHub because you mentioned you would be interested in contribute to fix. Let me know otherwise.
