### ISSUE TITLE
Feat: Introduce Resources for Interview Preparation

### ISSUE THREAD

**Issue by nora-weisser** [WomenCodingCommunity/WomenCodingCommunity.github.io#271]
### Is your feature request related to a problem? Please describe.
It would be beneficial for the community to have some resources for the interview preparation and job search on our website: https://womencodingcommunity.com/program-interview-preparation. Initial list of resources is already gathered and compiled. You can find it here: https://docs.google.com/document/d/1e5gZy3sZCaRfCghr9erpNuHC3a2dUSsMAUrDTQnbgSs/edit?usp=sharing 

### Describe the solution you'd like
1. Create a design for this change
2. Implement solution

**Comment by khairahscorner** [comment]
@lilyndk I'd appreciate your thoughts on this please, if there's any existing design we already have that would be great to reuse for the kind of content in the attached document. Thank you! 🙏
