### ISSUE TITLE
feat: Add Upcoming Events for July

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#277]
### Is your feature request related to a problem? Please describe.
We have 4+ upcoming events on Meetup: https://www.meetup.com/women-coding-community/events/. It'd be good to highlight the upcoming ones for July on the website.

### Describe the solution you'd like
July events added to the website, events details can be found [here](https://www.meetup.com/women-coding-community/events/).

**Note**: Please also add this event for July 17: https://www.meetup.com/women-coding-community/events/301584337/

**Comment by swetha-charles** [comment]
Hey - I'd like to take a look at this!

**Comment by khairahscorner** [comment]
@swetha-charles I have assigned the issue to you, please let me know if you have any questions and can work on this before June ends, thank you!
