### ISSUE TITLE
blog: Harnessing Generative AI 

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#281]
### Blog Metadata

Please provide the following information:

* Title: Harnessing Generative AI 
* Author: Sahana Venkatesh
* Position / Company: Software Engineer, Wayve
* Date: 1 July 2024 
* Short description: Generative AI, a transformative technology, has seen rapid advancements and widespread adoption in recent years. Major tech companies and startups are in a competitive race to develop superior models, while businesses and governments explore its applications and implications  My journey with GenAI began with a Hackathon for Social Good, creating Anxi-Aid, a tool utilizing AI for personalized anxiety management plans. This blogpost highlighted the potential of Generative AI in enhancing lives. To harness this technology, I walk through how one needs to understand use case, master prompt engineering, and leverage existing tools like OpenAI’s API.
* Google doc Link with the content: https://docs.google.com/document/d/13W0nyEjCzwxeSa3x_TdOXO_kr2DhXgNBO8SwUox3TYk/edit
* Category: ML

### Banner image
![image - Sahana Venkatesh](https://github.com/Women-Coding-Community/WomenCodingCommunity.github.io/assets/170346454/8137078a-7edd-41a6-9bc6-da5456c8909f)

Please include the banner image link for your post as a suggestion.
Keep in mind the image should be free or your own image creation.
In case you don't have any, the team can suggest.

Is there other images you want to include the content? Please include their links here also.

**Comment by dricazenck** [comment]
Check [PR](https://github.com/Women-Coding-Community/WomenCodingCommunity.github.io/pull/253) how to create a new blog.
