### ISSUE TITLE
blog: From CV to Job Offer: essential Tips for Software Engineer Interview Success

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#282]
### Blog Metadata

Please provide the following information:

* Title: From CV to Job Offer: essential Tips for Software Engineer Interview Success
* Author: Adriana Zencke Zimmermann
* Position / Company: Tech Lead at Centric Software 
* Date: 1st July 2024 
* Short description: Essential Tips for Software Engineer Interview Success
* Google doc Link with the content: https://docs.google.com/document/d/11NPTjaPLpzjVegIR_Dboeazcsf89PMce3eFAeC5KoZg/edit#heading=h.z2fu0dochmsv
* Category: Interview tips 

### Banner image
![mac-coffee-notes - Adriana Zenck Zimmermann (Drica)](https://github.com/Women-Coding-Community/WomenCodingCommunity.github.io/assets/170346454/2f3703a1-cb21-430d-908f-368f2ad988c5)

Please include the banner image link for your post as a suggestion.
Keep in mind the image should be free or your own image creation.
In case you don't have any, the team can suggest.

Is there other images you want to include the content? Please include their links here also.

**Comment by dricazenck** [comment]
Check [this one](https://github.com/Women-Coding-Community/WomenCodingCommunity.github.io/pull/253) how to create a new blog.
