### ISSUE TITLE
feat: Create "About" page for Mentorship

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#31]
### Is your feature request related to a problem? Please describe.
Create the About page for Mentorship on the navbar**_(Mentorship >> About)_**

**Please assign yourself to the task if working on it🙏**

### Describe the solution you'd like
- Design: https://www.figma.com/file/ncdevYZK7NGuTK3hc6mP4e/Design-Kit-Draft-(WCC)?type=design&node-id=54821-25572&mode=design&viewport=2608%2C-276%2C0.19&t=0KxB8FJuumD2KskU-0

- Content: https://docs.google.com/document/d/1PJjyWfgi3r-awNzJyISR2tVgrLXpSgpoX809rkwx1Dg/edit#heading=h.78q4sam49eix

- Reference: https://womenwhocode.github.io/london/

**Comment by nverbic** [comment]
assigned @nverbic
