### ISSUE TITLE
Add book recommendation for mentor : Olga Volkova

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#310]
### Task
Add recommendations for **Olga Volkova** in Resources section.
(Use the same format that has been used for other mentors e.g. Eleonora)

**Books**
[Designing Machine Learning Systems](https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/) 
[Machine Learning System Design Interview](https://www.amazon.co.uk/Machine-Learning-System-Design-Interview/dp/1736049127) 

**Resources tab**
![image](https://github.com/user-attachments/assets/b5f54ef5-c521-413d-8215-ec1e021b0246)

### Acceptance criteria
Screenshot of the resources tab

**Comment by OVolkova** [comment]
Could I please also add one more book to the list:
[Designing Data-Intensive Applications](https://dataintensive.net/)
