### ISSUE TITLE
feat: Create Mentorship Code of Conduct Page

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#32]
### Is your feature request related to a problem? Please describe.
Create the page for code of conduct for mentors and mentees **_(Mentorship >> Code of Conduct)_**

**Please assign yourself to the task if working on it🙏**

### Describe the solution you'd like
- Reference: [This page](https://womenwhocode.github.io/london/code-of-conduct) but with the new community colour palette

- Design: Similar to reference above but with the color palette from this: https://www.figma.com/file/ncdevYZK7NGuTK3hc6mP4e/Design-Kit-Draft-(WCC)?type=design&node-id=55033-25508&mode=design&viewport=2608%2C-276%2C0.19&t=0KxB8FJuumD2KskU-0

- Content: To be updated but will be in this document: https://docs.google.com/document/d/1PJjyWfgi3r-awNzJyISR2tVgrLXpSgpoX809rkwx1Dg/edit#heading=h.78q4sam49eix

**Comment by goelsonali** [comment]
Assign to @goelsonali
