### ISSUE TITLE
bug: old link on the mentorship slide

### ISSUE THREAD

**Issue by buketkonuk** [WomenCodingCommunity/WomenCodingCommunity.github.io#337]
### Describe the bug
On the below pdf document:
https://drive.google.com/file/d/1QfM-zCk-_LSR8rrfrawyog-bM_n7BFbG/view
when you click on <Take a moment to browse through the mentors who align with your goals and interests.> the link on "mentors" takes you to 404

![image](https://github.com/user-attachments/assets/419cbc8e-77b1-4e67-9947-9f530643c7d6)

![image](https://github.com/user-attachments/assets/2a0d6118-1c40-48a1-9076-6f37d8e8790a)

### To Reproduce
1. Go to 👍 https://womencodingcommunity.com/mentorship-resources
2. Click on 👍 "mentees guide"
3. Scroll down to :
<Take a moment to browse through the mentors who align with your goals and interests.>
click on "mentors"
5. See error

### Expected behavior
* The link should be directed to:
https://womencodingcommunity.com/mentors

* and all other links should be validated if they are with the correct domain, for example 

### Impact

- [ ] The bug affects minor functionality.

**Comment by dricazenck** [comment]
@goelsonali do you still have the original document to update this link?

**Comment by goelsonali** [comment]
yes i have it i will update it

**Comment by goelsonali** [comment]
Raised the PR with the new links to the new pdf on the drive
