### ISSUE TITLE
Navbar Improvements

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#34]
### Describe the bug
- "Programms" menu item also needs to be updated to the British spelling "Programmes".
- [Optional] Currently, the navbar horizontally extends the page if the dropdown for the last nav menu item ("About") is clicked (more visible on smaller screens).

### To Reproduce
1. Go to https://womencodingcommunity.github.io/
2. Check Menu Items on the Navbar Menu
3. Click on "About" menu item

### Expected behavior/Proposed Solution
- "Programms" updated to "Programmes"
- Styling can be updated for the Dropdown component to shift more towards the left if it's for the last menu item

### Screenshots
<img width="1440" alt="Screenshot 2024-04-24 at 7 17 47 am" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/38109438/3ab76691-c505-497c-a47d-e3bbc035fac2">
<img width="1440" alt="Screenshot 2024-04-24 at 7 19 15 am" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/38109438/06d85ecf-9839-413a-a895-028dde7459ea">

### Desktop
 (please complete the following information):
 - OS: Mac
 - Browser: Chrome
 - Version:

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [x] The bug is a cosmetic issue.

### Related Issues/PRs
If you know of any related issues or pull requests, link them here.

### Proposed Solution (optional)
If you have any ideas on how to fix the bug or potential areas to investigate, suggest them here.

### Your Contribution (optional)
If you're able and willing to contribute a fix, mention it here.

**Comment by ssssoz** [comment]
Happy to take this one on if no one takes it!

**Comment by lilyndk** [comment]
@sssoz just add a comment if you want to take this task. And I'll assign it to you :)

**Comment by ssssoz** [comment]
@lilyndk would like this one please!

**Comment by lilyndk** [comment]
assigned to you :) @sssoz
