### ISSUE TITLE
blog: Full Stack Developer at InnoAl Tech solution

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#346]
### Blog Metadata

Please provide the following information:

* Title: Full Stack Developer at InnoAl Tech solution
* Author: Arzu Caner 
* Position / Company: Full Stack Developer 
* Date: 27th September 2024
* Short description: I wrote about my Al DevCamp journey
* Google doc Link with the content: https://docs.google.com/document/d/15QyBn8rBKolyaoLnOdD3qQJkVzQGzxu07E4nF8itHuA/edit?usp=sharing
* Category: Personal Experience 

### Banner image

Please include the banner image link for your post as a suggestion.
Keep in mind the image should be free or your own image creation.
In case you don't have any, the team can suggest.

**Please try to ensure the banner image is of aspect ratio of 16:9 (e.g size 1024px by 576px) or higher.**

https://drive.google.com/file/d/1U0bsYXt7KCIlAhSN7U60VdKwP_ZIZ1zl/view

Is there other images you want to include the content? Please include their links here also.

**Comment by jbabahin** [comment]
Hi there, could we get help on posting this?

**Comment by khairahscorner** [comment]
Assigned to Laura Leigh

**Comment by lcleigh** [comment]
I'm having a look at this one :)

**Comment by khairahscorner** [comment]
> I'm having a look at this one :)

Perfect, thank you @lcleigh ! Please feel free to reference any of the previous blogs or this PR #358
