### ISSUE TITLE
feat: Add icons to homepage programs CTAs

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#35]
Add these icons to the CTAs:

![Group 2608543](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/d182bc6b-56fa-4687-b375-d8cb2c2e4d7d)

We're using Google's icon library: https://fonts.google.com/icons

**Comment by lilyndk** [comment]
Just discussed this with Sophy and she will work on this.

**Comment by ssssoz** [comment]
On it
