### ISSUE TITLE
test: Update Tests for Code of Conduct page 

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#36]
### Description
[**This file**](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/blob/main/test/assets/code_of_conduct.test.js) is about mentorship code of conduct and needs to be update for the new changes here https://womencodingcommunity.com/mentorship-code-of-conduct 

But the ideal page would look like this and tests are working as expecting: 
https://womenwhocode.github.io/london/code-of-conduct 
![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/d8735e3b-c8c5-4e23-ae5c-f0ef90a383aa)

**Comment by KayTV** [comment]
I'll take this one

**Comment by dricazenck** [comment]
> I'll take this one

The problem was not the test but the missing implementation. So this will be resolved after my pr is merged. If you want to create more tests for this page, and improve this one, because right now is not using the html file for mentors but mocked html. Let me know what what do you prefer.
