### ISSUE TITLE
FAQ section : Add question/answer regarding updating mentor profile

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#362]
### Task
Add a new question and answer to the FAQ section on how to update mentor profile.

**Question**
How can I update my mentor profile?
**Answer**
Simply fill out our [Update my Mentor Profle](https://docs.google.com/forms/d/e/1FAIpQLSdaFCi3YI3SIxajQtV3aC6DgHwRZFc1ZHY0j5Z2bY_OaZfRkQ/viewform) form, and we'll manage all the updates for you.

### Acceptance criteria
Screenshot of the FAQs

**Comment by Amenawon** [comment]
Hey @mads6879 , can I please be assigned this ticket :)
