### ISSUE TITLE
blog: Microservices Paradise

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#374]
### Blog Metadata

Please provide the following information:

* Title: Microservices Paradise
* Author: Irina Kamalova 
* Position / Company: VP Lead Software Engineer
* Date:4th November 2024 
* Short description: Microservices Paradise
* Google doc Link with the content: https://drive.google.com/open?id=1gH4kd2-KeH8fbp2rAefJm0ewZVGlZ79N
* Category: N/A

### Banner image

Please include the banner image link for your post as a suggestion.
Keep in mind the image should be free or your own image creation.
In case you don't have any, the team can suggest.

https://drive.google.com/open?id=18KxFLBFWcrG3peRtiEBOOywQnwF27pMI

**Please try to ensure the banner image is of aspect ratio of 16:9 (e.g size 1024px by 576px) or higher.**

Is there other images you want to include the content? Please include their links here also.

**Comment by khairahscorner** [comment]
Assigning to @Amenawon , thank you! 🙏

**Comment by Amenawon** [comment]
Hey, can I be assigned to this 👯

**Comment by khairahscorner** [comment]
@Amenawon checking if you are still able to work on this issue?

**Comment by Amenawon** [comment]
Yes yes, i will submit a pr soon
