### ISSUE TITLE
blog: Tailoring your career quarterly

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#375]
### Blog Metadata

Please provide the following information:

* Title:Tailoring your career quarterly
* Author:Irina Kamalova 
* Position / Company: VP Lead Software Engineer @ JPMorgan Chase
* Date: 4th November 2024 
* Short description: Tailoring your career quarterly
* Google doc Link with the content: https://drive.google.com/open?id=1MKNGzDgMBRurakr1bBeldhl78Vy0dXSY
* Category:N/A

### Banner image

Please include the banner image link for your post as a suggestion.
Keep in mind the image should be free or your own image creation.
In case you don't have any, the team can suggest.

https://drive.google.com/open?id=1GCQqhqauzTpnHfgGfNIvoryIar8ByN6G

**Please try to ensure the banner image is of aspect ratio of 16:9 (e.g size 1024px by 576px) or higher.**

Is there other images you want to include the content? Please include their links here also.

**Comment by gillian-black** [comment]
Hey @khairahscorner I can take this one as long as it's cool if it's done tomorrow? My first time contributing so I'll review the docs today :)

**Comment by khairahscorner** [comment]
@gillian-black that's totally fine! I have assigned the issue to you now, thank you🚀 
If you have any questions, please feel free to tag me or give me a shout on Slack!

**Comment by gillian-black** [comment]
@khairahscorner I came back from the weekend and my PR was merged with no notice. I'm in Toronto so it's early in my day.  I already removed the unused assets and will create a new PR.

**Comment by khairahscorner** [comment]
@gillian-black no worries at all! Your PR was already good to go, it just needed some extra cleanup that could be done in a different PR.
I left a comment on the PR as a notification, so that the blogpost could go live
