### ISSUE TITLE
bug: The event showing on the website is incorrect 

### ISSUE THREAD

**Issue by goelsonali** [WomenCodingCommunity/WomenCodingCommunity.github.io#378]
### Describe the bug
Under the Latest Events section on the home page, 
It is showing the incorrect Date + past meet-up event

### To Reproduce
1. Go to https://womencodingcommunity.com/
2. Scroll down to the "Latest Event" Section.
3. Check the event listed 
4. Now click the meet-up event it do not match up.

### Expected behavior
It should display correct event.

### Screenshots
<img width="1032" alt="Screenshot 2024-11-07 at 21 14 32" src="https://github.com/user-attachments/assets/6a0feaea-5e8a-4c41-86eb-03c656cb600a">

### Reproducibility
- [ ] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

### Related Issues/PRs
If you know of any related issues or pull requests, link them here.

### Proposed Solution (optional)
If you have any ideas on how to fix the bug or potential areas to investigate, suggest them here.

### Your Contribution (optional)
If you're able and willing to contribute a fix, mention it here.

**Comment by Amenawon** [comment]
@goelsonali  Hey ! could you please assign it to me ! :)

**Comment by khairahscorner** [comment]
Done @Amenawon If you could help add the rest of November events too, that'll be super!🚀 
All events are at https://www.meetup.com/women-coding-community/events/

We have some automation scripts as well that can be run to help with the import, located in the `/tools` folder

**Comment by Amenawon** [comment]
for sure, thank you
