### ISSUE TITLE
Mentee feedback added for mentor - Busra

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#381]
### Task
Add mentee feedback for the mentor
**Note** : Mentee has only rated the mentor and not added any feedback message

Mentee - Harini Balaji

Mentor - Busra Ecem Sakar

Type - Ad-hoc

Feedback - <<_**Mentee has not added any feedback message and has only rated the mentor. Hence either leave the feedback field empty OR remove it from the display if that's possible**_>>

Rating - 5

### Acceptance criteria
Screenshot of the mentee feedback

**Comment by Amenawon** [comment]
hey! can i be assigned this?

**Comment by khairahscorner** [comment]
Assigned @Amenawon

**Comment by dricazenck** [comment]
@mads6879 this attribute should be mandatory, could you fix the form please?

**Comment by dricazenck** [comment]
For this feedback it can be empty. But just score we agreed in the past that was not enough.
