### ISSUE TITLE
blog: A Simple Walkthrough of Kubernetes Pod Creation By Madhura Chaganty

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#389]
### Blog Metadata

Please provide the following information:

* Title: A Simple Walkthrough of Kubernetes Pod Creation
* Author: Madhura Chaganty
* Position / Company: Engineering Manager @ Elliptic
* Date: 3rd Dec 2024
* Short description: Kubernetes (or K8s) has no shortage of resources and guides, yet diving into its complexities can still feel overwhelming, especially for beginners. This blog is my attempt at understanding and simplifying this crucial process of how a Pod, the fundamental unit of deployment in K8s, progresses from a simple **YAML definition** to a fully **Running** state in the cluster.
* Google doc Link with the content: https://docs.google.com/document/d/1bUclrl46Dvd4gvZEVzCsmddcKA-YvG9K
* Category: #kubernetes

### Banner image
https://drive.google.com/drive/folders/1RwR-qGxTwyPjsnx9sY8mQLU31q3-iWC60fILKidnDIfBQ-CnFitdFoJP1HIufcI6j_lDQCXg

### Notes
Please include the codes with code formatting

Is there other images you want to include the content? Please include their links here also.

**Comment by BusraEcemSakar** [comment]
Can I work on this?

**Comment by khairahscorner** [comment]
Assigned @BusraEcemSakar thank you!🚀
