### ISSUE TITLE
feat: Study Groups Page

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#41]
### Is your feature request related to a problem? Please describe.
Create the page for Study Groups under Programmes on the navbar **_(Programms >> Study Group)_**

**For Now, the page can be moved to  **_(Mentorship >> Study Groups)_** and the design below is used.**

**Please assign yourself to the task if working on it🙏**

### Describe the solution you'd like
- Design: Can look similar to [this design](https://www.figma.com/file/yurqdzFK0hTKRGaO4TAeTU/Copied-Design?type=design&node-id=0-1&mode=design&t=yT1XdmmVMbjMLg9K-0) but with the [new community color palette](https://www.figma.com/file/ncdevYZK7NGuTK3hc6mP4e/Design-Kit-Draft-(WCC)?type=design&node-id=47909-2&mode=design&viewport=2608%2C-276%2C0.19&t=0KxB8FJuumD2KskU-0)
  - _**Suggestions**_: The introductory contents section can be the first section

- Content: WIP https://docs.google.com/document/d/1PJjyWfgi3r-awNzJyISR2tVgrLXpSgpoX809rkwx1Dg/edit#heading=h.n5mqp114sry0

**Comment by lilyndk** [comment]
@khairahscorner I guess there's still no content for this?

**Comment by khairahscorner** [comment]
@lilyndk Yeah, but maybe for now, we can move it to under "Mentorship" and feature the Mentorship study groups instead. The design for that is [**here**](https://www.figma.com/file/yurqdzFK0hTKRGaO4TAeTU/Copied-Design?type=design&node-id=0-1&mode=design&t=yT1XdmmVMbjMLg9K-0)

**Comment by lilyndk** [comment]
Thanks for the reply @khairahscorner . @dricazenck has added some text to the study group page in the #86 PR.

**Comment by goelsonali** [comment]
Suggestion, Can we create google forms per study group and link them on website and enable and disable then when we need ?

**Comment by khairahscorner** [comment]
Closing this issue since the page has been created, and #123 is open
