### ISSUE TITLE
bug: Update links on Home page, Opportunities & Programmes section

### ISSUE THREAD

**Issue by nverbic** [WomenCodingCommunity/WomenCodingCommunity.github.io#55]
### Describe the bug
Under Home page, under Opportunities and Programme sections, update the links for the following pages:
 - Resume clinic, Mock interviews and Leetcode so that they link to the /program-interview-preparation page (jump on the specific section of the page)

### To Reproduce
1. Go to Home page
2. Scroll down to Opportunities and Programmes
3. Click on the following links:
  -  Resume clinic
  -  Mock interviews
  -  Leetcode

### Expected behavior
Links of the CV clinic, Mock interviews and Leetcode should link to the appropriate section on the
 /program-interview-preparation page

### Screenshots
<img width="1462" alt="image" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/d3e8457a-1929-4eff-9b77-e14073548e55">

<img width="907" alt="image" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/085b2f21-92e3-4902-8bc4-ce78b3ab2bc0">

### Desktop (please complete the following information):
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 124.0.6367.61 (Official Build) (64-bit)

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [x ] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

**Comment by Deejarh** [comment]
Assign to @deejarh

**Comment by dricazenck** [comment]
I fixed that yesterday. You can check the website.

**Comment by dricazenck** [comment]
> Assign to @Deejarh

Sorry @Deejarh I didn't see the issue and fixed around the afternoon. Please check for other issues.
