### ISSUE TITLE
Add description to the 'Benefits for joining' LeetCode

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#66]
### Task
On the LeetCode page, there are bullet points for benefits of joining. It would be good to have some description for it. 

### Page URL
https://womencodingcommunity.github.io/program-interview-preparation#leetcode

### Description to add against the bullet points
Benefits of joining:
Collaborative learning - Practice problems, share solutions and strategies
Accountability and motivation - Set goals, track progress and engage with peers
Gain confidence - Build confidence to approach a problem in a structured manner
Different perspectives- Exchange different problem solving approaches

### Acceptance criteria
Screenshot of the page showing the benefits with description listed above

**Comment by parisa-0** [comment]
I can take this one
