### ISSUE TITLE
bug: fix homepage programmes anchor links

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#71]
These links need to be fixed to "jump" to the right sections on the program-interview-preparation page:

<img width="1553" alt="Screenshot 2024-04-25 at 09 49 31" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/f226f4d4-7973-425b-9d8f-0b7313862da6">

**Comment by ssssoz** [comment]
@lilyndk I can take this one

**Comment by lilyndk** [comment]
Thank you @sssoz ! please go ahead with the fix
