### ISSUE TITLE
bug: Improve responsive menu on smaller viewports 

### ISSUE THREAD

**Issue by ssssoz** [WomenCodingCommunity/WomenCodingCommunity.github.io#78]
### Describe the bug

- Navbar
    - Menu’s subitems content (e.g. Mentorship > About / Mentors / Resources...) have a left-hand-side light grey border that looks a bit off due to the partial border-radius — remove this 

### To Reproduce

1. Go to http://127.0.0.1:4000/
2. Reduce browser’s window size or use browser’s inspector & toggle to device toolbar to emulate different viewports 
3. Click the hamburger menu to see its mobile version 
 
### Expected behavior

These are mostly cosmetic updates (see screenshots below).

#### Nav 

<img width="498" alt="Screenshot 2024-04-25 at 10 21 52" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/6668406/43dfc3cf-d43e-4ff3-a474-b95174658868">

### Desktop (please complete the following information):
 - OS: MacOS Sonoma
 - Browser: Chrome 
 - Version: 124.0.6367.61 (Official Build) (arm64)

### Reproducibility

- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact

- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [x] The bug is a cosmetic issue.

### Proposed Solution (optional)

- Nav border-radius: don’t believe there’s a built-in Bootstrap class for this, just add custom CSS to reduce radius to `0`

**Comment by lilyndk** [comment]
@sssoz Great catch! Can you separate this into two bug tickets? So we have separate tickets for the 'button issue' and the 'nav issue'. Thanks!

**Comment by lilyndk** [comment]
@sssoz and yes, just write in the comments if you're starting work on these issues.
Just note that @nverbic is working on some style changes for those CTAs in this ticket: https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/77

**Comment by ssssoz** [comment]
> @sssoz Great catch! Can you separate this into two bug tickets? So we have separate tickets for the 'button issue' and the 'nav issue'. Thanks!

Split off into #79
