### ISSUE TITLE
bug: Improve responsive on Mentorship Programme 'About' page 

### ISSUE THREAD

**Issue by ssssoz** [WomenCodingCommunity/WomenCodingCommunity.github.io#79]
### Describe the bug

- [Mentorship Programme page](https://womencodingcommunity.github.io/mentorship)
    - Copy from `You should apply to be a mentor if you:` to `Check our Mentors` need padding 
   -`Check our Mentors` and `Join as a Mentor` buttons don't resize to the same size on smaller viewports 

### To Reproduce

1. Go to http://127.0.0.1:4000/
2. Reduce browser’s window size or use browser’s inspector & toggle to device toolbar to emulate different viewports 
3. Click on Mentorship > About to see Mentorship Programme page 
 
### Expected behaviour

These are mostly cosmetic updates (see screenshot below).

#### [Mentorship Programme page](https://womencodingcommunity.github.io/mentorship)

<img width="499" alt="Screenshot 2024-04-25 at 10 13 25" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/6668406/a56e5074-abd0-4278-b313-d4cf5719702c">

### Desktop (please complete the following information):
 - OS: MacOS Sonoma
 - Browser: Chrome 
 - Version: 124.0.6367.61 (Official Build) (arm64)

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [x] The bug is a cosmetic issue.

### Related Issues/PRs

See #77 as it affects the same buttons 

### Proposed Solution (optional)

- Mentorship content padding: just need to wrap with `container` or `container-fluid` or simply remove redundant `row`s and `col-12`s around text (as they’re not necessary here) 
- Mentorship buttons: move buttons into their corresponding `<div>`s (maybe make them into `sections`), and use matching HTML elements; both should be an anchor `<a>`

**Comment by lilyndk** [comment]
Fixed in https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/77
