### ISSUE TITLE
bug: fix page min-height

### ISSUE THREAD

**Issue by lilyndk** [WomenCodingCommunity/WomenCodingCommunity.github.io#80]
Fix page min-height to have the footer always bottom aligned.

A prominent issues on pages with little content where whitespace appears beneath the footer:

<img width="1320" alt="Screenshot 2024-04-25 at 11 04 30" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/26842896/d40fc161-b2a2-4f69-9b3c-3c15cd5dc382">

**Comment by lilyndk** [comment]
@sssoz Perhaps you want to take on this task? :)

**Comment by ssssoz** [comment]
Sure, I’ll take it

**Comment by ssssoz** [comment]
@lilyndk Sorry, I can't take it until later tonight actually — if that’s OK

**Comment by lilyndk** [comment]
gotcha, yes that's okay :) thank you! @sssoz

**Comment by MitaliShah** [comment]
I can take this one!

**Comment by lilyndk** [comment]
@MitaliShah, fyi @sssoz had mentioned earlier that she would work on it as noted in the comments :)

**Comment by MitaliShah** [comment]
Sorry, I didn't see that! @lilyndk

**Comment by lilyndk** [comment]
@MitaliShah No worries. Fyi in case you're interested in taking this task, I just created this frontend menu bug: https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/112

**Comment by khairahscorner** [comment]
@lilyndk the comments from @sssoz were from a couple of days ago, that's why I removed the assignment since it was still open and @MitaliShah was open to contributing

**Comment by lilyndk** [comment]
@khairahscorner ah ok got it, sorry. Yeah I guess @sssoz wasn't able to do the task a couple of days ago, which is totally fine :). So yeah @khairahscorner @MitaliShah feel free to work on it if you have time :)

**Comment by ssssoz** [comment]
Sorry, got a bit overwhelmed with work and couldn't get this done, forgot to update that here! Please go ahead.

**Comment by dricazenck** [comment]
Solved by the pull request #120
