### ISSUE TITLE
Add 'What are we reading' to the Book club page

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#95]
### Task
Add  **What we are reading** section to the Book club page  https://womencodingcommunity.com/program-book-club

### What we are reading
[The Pragmatic Programmer: From Journeyman to Master](https://www.goodreads.com/book/show/4099.The_Pragmatic_Programmer), Andrew Hunt & David Thomas

Essential guide for creating working and maintainable code amidst the complexities of modern software development

### Acceptance criteria
Screenshot showing the newly added section on the Book club page.

**Comment by parisa-0** [comment]
I can take this one!
