### ISSUE TITLE
doc: Add Ana Nogal as a mentor 

### ISSUE THREAD

**Issue by mads6879** [WomenCodingCommunity/WomenCodingCommunity.github.io#96]
### Task

Add Ana Nogal as a mentor to the list of mentors
URL - https://womencodingcommunity.com/mentors

Reference: https://womenwhocode.github.io/london/mentors (helpful to get mentor details)

### Acceptance Criteria
- Screenshot showing Ana Nogal listed as mentor
- Screenshot of the filtered list when Ana Nogal is searched

**Comment by parisa-0** [comment]
I can take this one!
