### ISSUE TITLE
doc: Update core tem members

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#97]
Not all team leaders are listed and need to be update the page 

Please include the following team members:

- Abhipsa Mishra - Leader
- Silke Nodwell - Leader
- Ekaterine Oshkhereli - Leader

The photos and complete details could be asked for tem on our slack.

**Comment by parisa-0** [comment]
I can take this one, have asked team on slack for details

**Comment by parisa-0** [comment]
I've create a pull request for Silke and Abhipsa #132, will create a new one for Eka once I get her details

**Comment by dricazenck** [comment]
Please include `Ekaterine Oshkhereli`, before Airat Yusuff. 

And we also have a **new Leader** 🙈  

**Sonali Goel**
Position: Senior/Lead Engineer at Yoox-Net-a-porter

![image](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/3664747/bce4a84c-540a-4f39-be1b-8d30a860f2ea)

Please include her as the last one 🙏
