### ISSUE TITLE
feat: Create Blog Page

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#98]
### Describe the solution you'd like
Our website is created using GitHub pages and it is very simple to introduce blog using GitHub pages. 

- create new item in menu Blog before About Us. 
- create layout proposal and before implementing check with team 
- create 1 publications of blog as example

### Describe alternatives you've considered

Talk to @khairahscorner and Arzu on slack for more details.

**Comment by parisa-0** [comment]
I can take this one

**Comment by khairahscorner** [comment]
thanks for creating the issue @dricazenck 
Want to work on this now but I don't have design skills to do a visual layout proposal, so I'll describe it here:

- the main blog page would have the common header on the website
- the blogposts will be listed in a similar design to [resources on the previous website ](https://womenwhocode.github.io/london/resources)
- for each blogpost itself, it would look similar [to this](https://womenwhocode.github.io/london/resources#:~:text=Events)

I'll do this as an initial setup and we can modify along based on ideas and suggestions

**Comment by lilyndk** [comment]
@khairahscorner I can work on a layout proposal today :) and add that to our shared Figma UI file.
