### ISSUE TITLE
Feat: Create existent Programmes

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#99]
It is necessary to include into our website the missing programmes: 

- Writing Programm/Club (talk with Rajani) 
- Speaking Programm/Club (talk with Madhura) 
- AI Track (talk to Julia)
- Machine Learning Programme (talk to Ying Liu)

### Template/ Layout 
Please follow the template of interview preparation programme as layout and organization of the content.

### Content 
Please talk with respective person on slack to ask for the contents, also to confirm the programme name. 

### Questions 
Please talk to @dricazenck

**Comment by KayTV** [comment]
I can take this one @dricazenck

**Comment by lilyndk** [comment]
Hi @KayTV, fyi a lot of component refactoring changes have been merged today related to branding re-design, thus please ensure to pull down latest changes from main branch, thanks.

**Comment by khairahscorner** [comment]
Unassigning this issue, as it has been pending without a merge for some time

**Comment by Deejarh** [comment]
@khairahscorner  i will like to work on this.
Is the content for the 'Other Programmes' available now?

**Comment by khairahscorner** [comment]
Yes @Deejarh please join the #proj-website channel and tag the respective coordinators listed above for each program to get the details.
Thank you for picking this up!🚀

**Comment by khairahscorner** [comment]
Not completed yet:
- Split programmes into separate pages
- Machine Learning programme still pending
